"""empty message

Revision ID: fe0625ace115
Revises: 
Create Date: 2021-09-08 16:04:00.283072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe0625ace115'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bean',
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('writer', sa.String(length=20), nullable=True),
    sa.Column('nameE', sa.String(length=20), nullable=False),
    sa.Column('nameK', sa.String(length=20), nullable=False),
    sa.Column('taste', sa.String(length=20), nullable=False),
    sa.Column('origin', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=50), nullable=False),
    sa.Column('price', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('num')
    )
    op.create_table('coffee',
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('writer', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('name2', sa.String(length=20), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('img', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('num')
    )
    op.create_table('member',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('pwd', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('merchandise',
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('writer', sa.String(length=20), nullable=False),
    sa.Column('engName', sa.String(length=50), nullable=False),
    sa.Column('krName', sa.String(length=50), nullable=False),
    sa.Column('price', sa.String(length=50), nullable=False),
    sa.Column('imgLink', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('num')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('merchandise')
    op.drop_table('member')
    op.drop_table('coffee')
    op.drop_table('bean')
    # ### end Alembic commands ###
